#!/bin/sh

DIR=$(dirname $(readlink -e -- "$0"))

echo "Downloading latest Neovim"
[ -f $DIR/nvim.appimage ] && rm $DIR/nvim.appimage
curl -Lo $DIR/nvim.appimage https://github.com/neovim/neovim/releases/latest/download/nvim.appimage && chmod u+x $DIR/nvim.appimage
